#if !canImport(ObjectiveC)
import XCTest

extension DynamicProgrammingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DynamicProgrammingTests = [
        ("testCoins", testCoins),
        ("testFibonacci", testFibonacci),
        ("testKnapsack", testKnapsack),
        ("testSquareMatrices", testSquareMatrices),
        ("testTargetSum", testTargetSum),
    ]
}

extension HeapTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HeapTests = [
        ("testChallenge1", testChallenge1),
        ("testChallenge3", testChallenge3),
    ]
}

extension LinkedListTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LinkedListTests = [
        ("testHasCyclesFalse", testHasCyclesFalse),
        ("testHasCyclesTrue", testHasCyclesTrue),
    ]
}

extension SortTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SortTests = [
        ("testQuickSort", testQuickSort),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DynamicProgrammingTests.__allTests__DynamicProgrammingTests),
        testCase(HeapTests.__allTests__HeapTests),
        testCase(LinkedListTests.__allTests__LinkedListTests),
        testCase(SortTests.__allTests__SortTests),
    ]
}
#endif
